data_source: http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv
artifcats:
  artifacts_dir : artifacts
  raw_local_dir : raw_local_dir
  raw_local_file : data.csv
  